src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

# from django.conf.urls import include

from django.urls import path, include
from django.contrib import admin

from django.views.generic import TemplateView

#importing from models apps

# from products.views import (
#     ProductListView,
#     product_list_view,
#     ProductDetailView,
#     ProductDetailSlugView,
#     product_detail_view,
#     ProductFeaturedListView,
#     ProductFeaturedDetailView
#     )

from .views import *

urlpatterns = [
	path('', home_page, name='home'),
	path('about/', about_page, name='about'),
	path('contact/', contact_page, name='contact'),
	path('service/', service_page, name='service'),
    path('login/', login_page, name='login'),
    path('register/', register_page, name='register'),
    path('bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
    path('products/', include("products.urls")),
    path('search/', include("search.urls")),
 #    path('featured/', ProductFeaturedListView.as_view()),
 #    path('featured/<int:pk>/', ProductFeaturedDetailView.as_view()),
 #    path('products/', ProductListView.as_view()),
 #    path('products-fbv/', product_list_view),
 #    # path('products/<int:pk>/', ProductDetailView.as_view()),
 #    path('products/<slug>/', ProductDetailSlugView.as_view()),
 #    path('products-fbv/<int:pk>/', product_detail_view),
	# path('call/', call_page),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.urls import path


from products.views import (
    ProductListView,
    ProductDetailSlugView,
    )

from .views import *
app_name = 'products'
urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('<slug>/', ProductDetailSlugView.as_view(), name='detail'),
]

src/search/urls.py
from django.urls import path
app_name = 'search'

from .views import (
    SearchProductView,

    )

urlpatterns = [
    path('', SearchProductView.as_view(), name='query'),
]

src/templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
 

src/templates/base/js.html
{% load static %}

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as products_url %}
{% url 'login' as login_url %}
{% url 'register' as register_url %}


<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-5">
      <div class='container'>
        <a class="navbar-brand" href="#">
          <img src="https://excellence.qa/wp-content/uploads/2018/06/logo-01.png" width="50%" height="50%" class="d-inline-block align-top" alt="" loading="lazy">

         </a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapseLink" aria-expanded="false" aria-label="Toggle Navigation">
        <span class="navbar-toggler-icon"></span>
         </button>


      <div class='collapse navbar-collapse' id='navbarCollapseLink'>
         <ul class="navbar-nav" >
          <li class="navbar-item {%if request.path == home_url%} active {% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {%if request.path == contact_url%} active {% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contact</a>
      </li>

      <li class="nav-item {%if request.path == products_url%} active {% endif %}">
        <a class="nav-link" href="{{ products_url }}">Products</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item {%if request.path == login_url%} active {% endif %}">
       <a class="nav-link" href="{{ login_url }}">Logout</a>
      </li>
    {% else %}
    <li class="nav-item {%if request.path == register_url%} active {% endif %}">
       <a class="nav-link" href="{{ register_url }}">Register</a>
      </li>
   
    <li class="nav-item {%if request.path == login_url%} active {% endif %}">
       <a class="nav-link" href="{{ login_url }}">Login</a>
      </li>
      {% endif %}
      
    </ul>
     {% include 'search/snippets/search-form.html' %}
</div>
</div>
</nav>